version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    container_name: clv-fastapi
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    container_name: clv-streamlit
    restart: always
    depends_on:
      - fastapi
